name: 'google_connectors'
version: '1.0.0'

profile: 'google'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  google_connectors:
    # Config indicated by + and applies to all files under models/microsoft/
    google:
      +materialized: table

# Define variables here
vars:
  googleads_campaign_performance_v_1_identifier: googleads_campaign_performance_v_1
  googleads_keyword_performance_v_1_identifier: googleads_keyword_performance_v_1
  googleads_ad_performance_basic_v_1_identifier: googleads_ad_performance_basic_v_1
  googleads_ad_performance_conversions_v_1_identifier: googleads_ad_performance_conversions_v_1
